apiVersion: apps/v1
kind: Deployment
metadata:
  name: gespracti
spec:
  selector:
    matchLabels:
      app: gespracti
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: gespracti
        tier: frontend
    spec:
      initContainers:
      - image: marinoqj/gespracti:1.0.1
        imagePullPolicy: Always
        name: war
        command:
          - "cp"
          - "/gespracti.war"
          - "/app"
        volumeMounts:
        - mountPath: /app
          name: app-volume
      containers:
      - image: tomcat:9.0.30-jdk11-openjdk
        name: tomcat
        command: ["catalina.sh", "run"]
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps
          name: app-volume
        ports:
        - containerPort: 8080
          protocol: TCP
      volumes:
      - name: app-volume
        emptyDir: {}


