


INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('1', 'CENTRO DE LIDERAZGO Y TECNOLOGÍA UPM');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('1', '484', 'MASTER EN LIDERAZGO INTERNACIONAL EN INGENIERÍA Y ARQUITECTURA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('1', '489', 'ESPECIALIZACION EN ORGANIZACIONES INTELIGENTES HACIA LA TRANSFORMACIÓN DIGITAL');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('2', 'E.T.S. Arquitectura');                            
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '89', 'Máster Universitario en Arquitectura');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '90', 'Máster Título Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '156', 'Doctorado Arquitectura');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '182', 'Programa Movilidad ETSI Arquitectura');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '224', 'Arquitecto');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '225', 'Grado en Fundamentos de  la Arquitectura');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '230', 'Master Universitario en Comunicación Arquitectónica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '231', 'Máster Universitario Conservación y Restauración del Patrimonio Arquitectónico');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '232', 'Máster Universitario en Análisis, Teoría e Historia de la Arquitectura');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '233', 'Máster Universitario en Construcción y Tecnología Arquitectónicas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '234', 'Master Universitario en Construcción y Tecnología de los Edificios Históricos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '235', 'Máster Universitario en Diseño de Instalaciones');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '236', 'Máster Universitario en Estructuras de la Edificación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '237', 'Máster Universitario en Estudios Superiores en Arquitectura y Urbanismo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '314', 'Grado Título Propio en Diseño de Interiores');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '318', 'Máster en Medio Ambiente y Arquitectura Bioclimatica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '321', 'Metodología y Gestión Bim de Proyectos, Construcción');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '333', 'Máster en Dirección Integrada de Proyectos de Edificación.');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '335', 'Master en Diseño y Arquitectura de Interiores');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '336', 'Master Universitario en Proyectos Arquitectonicos Avanzados');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '337', 'Doctorado en Proyectos Arquitectonicos Avanzados');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '339', 'MASTER EN REHABILITACION Y AHORRO ENERGETICO');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '341', 'Máster en Diseño de Iluminación Arquitectónica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '342', 'PERIFERIAS, SOSTENIBILIDAD Y VITALIDAD URBANA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '343', 'Máster Patología de la Edificación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '355', 'Master en Real Estate y Facility Management');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '357', 'Diseño Multimedia para la Comunicación Arquitectónica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '362', 'Medio Ambiente y Arquitectura Bioclimática - On Line');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '376', 'Doctorado en Construccion y Tecnologia Arquitectonicas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '409', 'Master In City Sciences');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '413', 'Direccion de Empresas Constructoras e Inmobiliarias');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '421', 'Infografía. Diseño Multimedia para la Comunicación Arquitectónica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '424', 'Master Instalaciones y Arquitecturas Interactivas y Efimeras');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '441', 'Master Universitario en Planeamiento Urbano y Territorial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '447', 'Cooperacion para El Desarrollo de Asentamientos Humanos Precarios');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '448', 'Plan Grado Visitantes Arquitectura');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '454', 'Master en Patrimonio Cultural en El Siglo Xxi: Gestión e Investigación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '455', 'Máster en Arquitecturas  Efímeras');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '458', 'Máster Advanced Infographics');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '472', 'Arquitectura, Moda y Diseño');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '473', 'Doctorado en Sostenibilidad y Regeneracion Urbana');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '478', 'MASTER EN FACHADAS TECNOLÓGICAS Y ENVOLVENTES SOSTENIBLES');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '519', 'DIRECCIÓN DE EMPRESAS CONSTRUCTORAS E INMOBILIARIAS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '537', 'MASTER IN ADVANCED STUDIES IN COLLECTIVE HOUSING');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('2', '538', 'DIRECCION INTEGRADA DE PROYECTOS DE EDIFICACION Y ACTIVOS INMOBILIARIOS');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('3', 'E.T.S.I. de Caminos, Canales y Puertos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '18', 'Ingeniero de Caminos, Canales y Puertos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '19', 'Ingeniero de Materiales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '20', 'Grado en Ingeniería de Materiales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '21', 'Grado en Ingeniería Civil y Territorial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '96', 'Máster Título Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '98', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '159', 'Doctorado Caminos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '192', 'Programa Movilidad  ETSI Caminos, Canales y Puertos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '271', 'Máster Universitario en Ingeniería de Caminos, Canales y Puertos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '272', 'Máster Universitario en Ingeniería de Materiales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '273', 'Máster Universitario en Sistemas de Ingeniería Civil');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '274', 'Máster Universitario Ingeniería de las Estructuras, Cimentaciones y Materiales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '320', 'Master en Gestion de Infraestructuras, Equipamientos y Servicios');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '338', 'Máster en Gestión Integrada de Proyectos de Ingeniería y Construcción');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '456', 'Doble Master en Iccp y en Sistemas de Ingenieria Civil');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '521', 'DOBLE GRADO EN INGENIERIA CIVIL Y TERRITORIAL Y EN ADE');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('3', '533', 'GRADO EN INGENIERIA CIVIL');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('4', 'E.T.S. Edificación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '49', 'Arquitecto Técnico');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '50', 'Grado en Edificación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '124', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '125', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '126', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '167', 'Doctorado Arquitectura Técnica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '206', 'Programa Movilidad ETS Edificación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '238', 'Máster Universitario en Gestión en Edificación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '239', 'Máster Universitario en Innovación Tecnológica en Edificación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '345', 'Master en Eficiencia Energética en la Edificación, la Industria y el Transporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '356', 'Doctorado en Innovacion Tecnologica en Edificacion');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '374', 'Doble Grado en Edificación y Administración y Dirección de Empresas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '400', 'Grado propio de intensificación en "Planificación y Gestión Inmobiliaria');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '460', 'Máster Universitario en Ejecución de Obras de Restauración y Rehabilitación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '503', 'DOBLE MÁSTER EN INNOVACIÓN TECNOLÓGICA EN EDIFICACIÓN Y EN EJECUCIÓN DE OBRAS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('4', '522', 'PLANIFICACIÓN Y GESTIÓN INMOBILIARIA');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('5', 'E.T.S. de Ingeniería Civil');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '72', 'Ingeniero Técnico de Obras Públicas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '143', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '144', 'Máster Título Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '173', 'Doctorado Obras Públicas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '189', 'Programa Movilidad ETS Ingeniería Civil');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '219', 'Master Infraestructuras');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '309', 'Máster Universitario en Planificación y Gestión de Infraestructuras');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('5', '334', 'Proyecto de Estructuras de Cimentación y Contención');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('6', 'E.T.S.I. Industriales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '22', 'Ingeniero Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '23', 'Ingeniero Químico');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '24', 'Ingeniero en Organización Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '25', 'Ingeniero en Automática y Electrónica Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '26', 'Grado en Ingeniería en Tecnologías Industriales, espc. Ingeniería Eléctrica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '27', 'Grado en Ingenieria Química');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '31', 'Máster Universitario en Ingeniería de la Energía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '101', 'Máster Habilitante Ingeniería Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '102', 'Máster Título Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '160', 'Doctorado Industriales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '181', 'Programa Movilidad ETSI Industriales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '198', 'Grado en Ingeniería en Tecnologías Industriales, espc. Ingeniería Electrónica y Automática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '199', 'Grado en Ingeniería en Tecnologías Industriales, espc. Ingeniería Mecánica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '200', 'Grado en Ingeniería en Tecnologías Industriales, espc. Organización');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '212', 'Grado en Ingenieria en Tecnologias Industriales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '223', 'Grado en Ingeniería de la Energía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '226', 'Master Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '287', 'Máster Universitario en Automática y Robótica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '288', 'Máster Universitario en Ciencia y Tecnología Nuclear');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '289', 'Máster Universitario en Economía y Gestión de la Innovación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '290', 'Máster Universitario en Electrónica Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '291', 'Máster Universitario en Ingeniería Acústica en la Industria y el Transporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '292', 'Máster Universitario en Ingeniería Ambiental');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '293', 'Máster Universitario en Ingeniería de la Energía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '294', 'Máster Universitario en Ingeniería de Organización');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '295', 'Máster Universitario en Ingeniería Eléctrica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '296', 'Máster Universitario en Ingeniería Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '297', 'Máster Universitario en Ingeniería Mecánica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '298', 'Máster Universitario en Ingeniería Química');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '299', 'Máster Universitario en Ingeniería Sísmica: Dinámica de Suelos y Estructuras');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '313', 'Máster Universitario en Plasma, Láser y Tecnologías de Superficie');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '322', 'Masters Degree in Numerical Simulation In Engineering With Ansys');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '324', 'Máster en Ingeniería Automoción');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '325', 'Master Universitario en Ingenieria Sismica: Dinamica de Suelos y Estructura');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '326', 'Máster en Administración y Dirección Internacional de Empresas (MBA Internacional)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '327', 'Máster en Administración de Empresas (MBA)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '328', 'Especialista en Mercados Regulados y Competencia');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '329', 'Especialista en Nuevas Fuentes de Financiación Empresarial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '330', 'MASTER UNIVERSITARIO EN INGENIERIA DE LA ORGANIZACION');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '332', 'Master en Calidad Total');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '340', 'Grado en Ingeniería de Organización');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '346', 'Master en Eficiencia Energética en la Edificación, la Industria y el Transporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '350', 'Máster Universitario en Ingeniería de Materiales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '352', 'International Master In Industrial Management');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '377', 'Master Universitario en Ciencia y Tecnologia Nuclear');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '390', 'Máster en Ingeniería de los Vehículos Híbridos y Eléctricos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '396', 'Doble Grado Ing en Diseño Industrial y Desarrollo Producto y en Ing Mecanica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '401', 'Master Universitario en Ingenieria de la Organizacion');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '403', 'Me3 - European Joint Masters In Management And Engineering');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '407', 'Doctorado en Ingenieria Quimica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '410', 'Doctorado en Economía y Gestión de la Innovación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '411', 'Doctorado en Ingenieria Mecanica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '430', 'Programa de Movilidad ETSI Industriales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '445', 'Doble Master Universitario en Ingenieria Industrial y en Ingenieria Sismica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '462', 'Doble Master Universitario en Ingenieria Industrial y en Automatica y Robot');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '463', 'ESPECIALISTA EN FINANZAS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '467', 'DOBLE MASTER UNIVERSITARIO INGENIERIA INDUSTRIAL - ELECTRONICA INDUSTRIAL');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '494', 'ANÁLISIS FINANCIERO');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '514', 'D.M.U. EN INGENIERÍA INDUSTRIAL Y EN CIENCIA Y TECNOLOGÍA NUCLEAR');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '516', 'Doble Master Universitario en Ingenieria Industrial y en Automatica y Robot');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('6', '531', 'GRADO EN INGENIERIA DE LA ENERGIA');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('7', 'E.T.S.I. de Minas y Energía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '28', 'Ingeniero de Minas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '29', 'Ingeniero Geólogo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '30', 'Ingeniero Técnico de Minas, espec. en Recursos Energéticos, Combustibles y Explosivos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '32', 'Grado en Ingeniería en Tecnología Minera');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '103', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '104', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '105', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '161', 'Doctorado Minas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '184', 'Programa Movilidad ETSI de Minas y Energía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '201', 'Grado en Ingeniería en Tecnología Minera (GITM)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '209', 'Grado en Ingeniería de los Recursos Energéticos, Combustibles y Explosivos (GIRECE)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '210', 'Grado en Ingeniería Geológica (GIG)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '275', 'Master en Eficiencia Energética en la Edificación, la Industria y el Transporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '276', 'Máster Universitario en Ingeniería de Minas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '277', 'Máster Universitario en Ingeniería Geológica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '278', 'Máster Universitario en Invest., Model. y Análisis del Riesgo en Medio Ambiente');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '279', 'Máster Universitario en Minería Sostenible');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '315', 'Grado en Ingeniería de la Energía (E.T.S.I. de Minas y Energía)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '349', 'Máster en Ingeniería, Petróleo y Gas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '412', 'Master Universitario en Ingenieria de Minas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '443', 'Master Universitario en Gestion de Desastres');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '526', 'Máster Universitario en Contaminación de Suelos y Aguas Subterráneas (MUCSA)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('7', '532', 'GRADO EN INGENIERIA DE LA ENERGIA');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('8', 'E.T.S.I. Navales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '35', 'Ingeniero Naval y Oceánico');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '36', 'Master Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '37', 'Grado en Ingeniería Marítima');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '109', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '110', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '111', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '163', 'Doctorado Navales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '227', 'Grado en Arquitectura Naval');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '305', 'Máster Universitario en Ingeniería Naval y Oceánica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '420', 'Programas de Movilidad ETSI Navales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('8', '465', 'Master en Aprovechamiento de las Energías Renovables Marinas (MAERM)');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('9', 'E.T.S. de Ingeniería y Diseño Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '62', 'Ingeniero Técnico Industrial, espc. en Electricidad');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '63', 'Ingeniero Técnico Industrial, espc. en Electrónica Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '64', 'Ingeniero Técnico Industrial, espc. en Mecánica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '65', 'Ingeniero Técnico Industrial, espc. Química Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '67', 'Grado en Ingeniería Eléctrica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '68', 'Grado en Ingeniería Electrónica Industrial y Automática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '69', 'Grado en Ingeniería Mecánica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '70', 'Grado en Ingeniería Química');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '71', 'Grado en Ingeniería en Diseño Industrial y Desarrollo del Producto');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '140', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '141', 'Máster Título Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '142', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '172', 'Doctorado Técnica Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '190', 'Programas Movilidad ETS de Ingeniería y Diseño Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '265', 'Máster Universitario en Ingeniería de Producción');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '266', 'Máster Universitario en Ingeniería Electromecánica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '267', 'Máster Universitario en Ingeniería en Diseño Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '399', 'Master en Energias Renovables y Medio Ambiente');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '402', 'GESTION INTEGRADA DE PROYECTOS DE CLIMATIZACION');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '406', 'Doble Grado en Ing. Eléctrica y en Ing. Eléctrica Industrial y Automática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('9', '415', 'Doble Grado Ing en Diseño Industrial y Desarrollo Producto y en Ing Mecanica');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('10', 'E.T.S. de Ingeniería Aeronáutica y del Espacio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '66', 'Grado en Ingeniería Aeroespacial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '148', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '149', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '150', 'Máster Título Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '175', 'Doctorado EIAE');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '193', 'Programa Movilidad ETS de Ingeniería Aeronáutica y del Espacio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '213', 'Grado en Gestión y Operación del Transporte Aéreo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '246', 'Máster Universitario en Sistemas del Transporte Aéreo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '247', 'Máster Universitario en Sistemas Espaciales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '308', 'Máster Universitario en Ingeniería Aeronáutica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '358', 'Materiales Compuestos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '393', 'Master Universitario en Matematica Industrial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('10', '479', 'Máster en Gestión de Sistemas Aeronáuticos');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('11', 'E.T.S.I Agronomica, Alimentaria y de Biosistemas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '365', 'Grado en Biotecnología');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '366', 'Grado en Ingeniería Agrícola');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '367', 'Grado en Ingeniería Alimentaria');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '368', 'Grado en Ingeniería y Ciencia Agronómica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '370', 'Grado en Ingeniería del Medio Natural');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '371', 'Grado en Ingeniería Agroambiental');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '373', 'Grado en Tecnología de las Industrias Agrarias y Alimentarias');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '378', 'Máster en Ingeniería Agronómica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '379', 'Máster en Ingeniería Alimentaria aplicada a la Salud');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '380', 'Máster Universitario en Agroingeniería');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '381', 'Máster en Biotecnología Agroforestal');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '382', 'Máster en Economía Agraria, Alimentaria y de los Recursos Naturales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '383', 'Máster en Física de Sistemas Complejos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '385', 'Máster Planificación de Proyectos de Desarrollo Rural y Gestión Sostenible');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '386', 'Máster en Producción y Sanidad Animal');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '387', 'Máster en Estrategias y Tecnologías para el Desarrollo. La cooperación en un mundo en cambio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '388', 'Máster en Tecnología Agroambiental para una Agricultura Sostenible');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '389', 'Máster en Jardinería y Paisajismo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '417', 'Programas de Movilidad - E.T.S.I de Ingenieria Agronomica, Alimentaria y de Biosistemas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '427', 'Doble Máster en Ingeniería Agronómica y Economía Agraria, Alimentaria y de Recursos Naturales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '439', 'Máster en Viticultura y Enología');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '442', 'Mu Estrategias y Tecnologias para El Desarrollo: la Cooperacion en Un Mundo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '446', 'Doctorado Tecnologia Agroambiental para Una Agricultura Sostenible');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '451', 'Master en Gestión de la Calidad Alimentaria');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '452', 'Ingeniero Técnio Agrícola Especialidad Hortofruticultura y Jardineria');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '453', 'Ingeniero Agrónomo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '459', 'Master en Biologia Computacional');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '468', 'Doctorado en Biotecnologia y Recursos Geneticos de Plantas y Microorganismo');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '477', 'Master Univ. Planificacion de Proyectos de Dllo Rural y Gestion Sostenible');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '481', 'Grado en Ciencias Agrarias y Bioeconomía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '482', 'Master en Ingeniería de Sistemas Agrarios');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '499', 'MASTER UNIVERSITARIO EN BIOTECNOLOGIA AGROFORESTAL');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('11', '529', 'MASTER UNIV EN TECNOLOGIA AGROAMBIENTAL PARA UNA AGRICULTURA SOSTENIBLE');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('12', 'Centro itdUPM (ETSI Agrónomica, Alimentaria y de Biosistemas)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('12', '436', 'Máster en Estrategias y Tecnologías para el Desarrollo');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('13', 'E.T.S. de Ingeniería de Montes, Forestal y del Medio Natural');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '33', 'Ingeniero de Montes');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '34', 'Licenciado en Ciencias Ambientales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '87', 'Grado en Ingeniería del Medio Natural');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '106', 'Máster en Técnicas de Lucha contra Incendios Forestales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '108', 'Máster en Gestión Sostenible de los Residuos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '162', 'Doctorado Montes');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '171', 'Doctorado Forestales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '176', 'Doctorado EIFMN');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '178', 'Grado Ingeniería Forestal');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '188', 'Programa Movilidad ETS de Ingeniería de Montes, Forestal y del Medio Natural');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '258', 'Máster Universitario El Agua en el Medio Natural. Usos y Gestión');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '259', 'Máster Universitario en Ingeniería de Montes');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '260', 'Máster Universitario en Restauración de Ecosistemas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '316', 'Ingeniero Técnico Forestal');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '348', 'GESTION DE RESIDUOS URBANOS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '414', 'Master Universitario en Gestion del Turismo Ecologico y Sostenible');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '437', 'Gestión Sostenible de los Residuos / Sustainable Waste Management');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '440', 'Grado en Ingeniería en Tecnologías Ambientales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '511', 'Master Universitario en Economia Circular');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('13', '517', 'Máster en Jardines Históricos y Servicios Ecosistémicos de la Infraestructura');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('14', 'E.T.S.I. de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '38', 'Ingeniero de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '39', 'Grado en Ingeniería de Tecnologías y Servicios de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '40', 'Grado en Ingeniería Biomédica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '112', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '113', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '114', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '164', 'Doctorado Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '195', 'Programa Movilidad ETSI de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '281', 'Máster Universitario en Energía Solar Fotovoltaica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '282', 'Máster Universitario en Ingeniería Biomédica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '283', 'Máster Universitario en Ingeniería de Redes y Servicios Telemáticos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '284', 'Máster Universitario en Ingeniería de Sistemas Electrónicos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '285', 'Máster Universitario en Ingeniería de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '286', 'Máster Universitario en Tratamiento Estadístico Computacional de la Información');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '323', 'DIRECCION Y ORGANIZACION SISTEMAS DE INFORMACION Y COMUNICACIONES');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '351', 'Máster Universitario en Ingeniería de Materiales');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '354', 'HUAWEI-UPM en Comunicaciones Móviles');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '364', 'Doctorado en Ingeniería Biomédica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '408', 'Doctorado en Ingeniería de Sistemas Telemáticos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '425', 'Teoria de la Señal y Comunicaciones');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '426', 'Master Universitario en Teoria de la Señal y Comunicaciones');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '449', 'Administracion y Direccion de Empresas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '461', 'Eit Digital Track On Software And Services Architecture');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '483', 'Doble Máster en Ingeniería de Telecomunicación y en Teoría de la Señal y Comunicaciones');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '501', 'DOBLE MASTER INGENIERIA TELECOMUNICACION Y EN REDES Y SERVICIOS TELEMATICOS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('14', '540', 'GRADO EN INGENIERIA DE TECNOLOGIAS Y SERVICIOS DE TELECOMUNICACION');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('15', 'E.T.S. de Ingeniería y Sistemas de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '74', 'Ingeniero Técnico de Telecomunicación, espc. en Sistemas Electrónicos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '75', 'Ingeniero Técnico de Telecomunicación, espc. en Sistemas de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '76', 'Ingeniero Técnico de Telecomunicación, espc. en Sonido e Imagen');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '77', 'Ingeniero Técnico de Telecomunicación, espc. en Telemática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '78', 'Grado en Ingeniería Electrónica de Comunicaciones');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '79', 'Grado en Ingeniería de Sistemas de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '80', 'Grado en Ingeniería de Sonido e Imagen');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '81', 'Grado en Ingeniería Telemática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '145', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '146', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '147', 'Máster Título Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '174', 'Doctorado Ingeniería de Sistemas y Servicios para las Sociedad de la Información');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '268', 'Máster Universitario en Ing. de Sist. y Serv. para la Sociedad de la Información');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '269', 'Máster Universitario en Ingeniería Acústica');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '431', 'Programa Movilidad ETS de Ingeniería y Sistemas de Telecomunicación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '435', 'Eit Digital Track On Internet Technology And Architecture');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '469', 'Master Universitario en Internet de las Cosas / Internet of Things');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('15', '474', 'Doble Grado en Ing.electronica de Comunicaciones y en Ing.telematica');


INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('16', 'E.T.S.I. Informáticos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '46', 'Grado en Matemáticas e Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '100', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '121', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '122', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '168', 'Doctorado F. Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '207', 'Grado en Ingeniería Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '301', 'Máster Universitario en Ingeniería del Software');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '302', 'Máster Universitario en Ingeniería Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '303', 'Máster Universitario en Inteligencia Artificial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '304', 'Máster Universitario en Software y Sistemas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '317', 'Ingeniero en Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '353', 'EIT Digital Master`s Programme in Data Science');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '395', 'Alumnos Programas Movilidad');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '419', 'Consultoria y Gestion de Empresas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '422', 'Master EIT Digital in Human Computer Interaction and Design');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '423', 'Doble Grado en Ingeniería Informática y ADE');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '490', 'Master Universitario en Ciencia de Datos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '492', 'Máster Interuniversitario en Métodos Formales en Ingeniería Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('16', '493', 'Master Universitario en Innovación Digital');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('17', 'E.T.S. de Ingeniería de Sistemas Informáticos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '44', 'Ingeniero Técnico en Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '82', 'Ingeniero Técnico en Informática de Gestión');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '83', 'Ingeniero Técnico en Informática de Sistemas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '84', 'Grado en Ingeniería de Computadores');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '85', 'Grado en Ingeniería del Software');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '123', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '127', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '128', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '129', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '155', 'Doctorado EU Informática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '196', 'Programa ERASMUS ETS de Ingeniería y Sistemas Informáticos.');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '222', 'Grado en Sistemas de Informacion');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '261', 'Mu en Desarrollo de Aplicaciones y Servicios para Dispositivos Móviles por la Universidad');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '262', 'Máster Universitaro en Ciencia y Tecnologías de la Computación');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '263', 'Máster Universitario en Ingeniería Web');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '264', 'Máster Universitario en Software de Sistemas Distribuidos y Empotrados');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '391', 'Master en Diseño y Desarrollo de Videojuegos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '475', 'Doble Grado Ingenieria Computadores y Tecnologias para Sociedad Informacion');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '476', 'Doble Grado Ingenieria de Software y Tecnologias para Sociedad Informacion');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('17', '513', 'Grado en Tecnologías para la Sociedad de la Informacion');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('18', 'E.T.S.I. Topografía, Geodesia y Cartografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '41', 'Ingeniero Técnico en Topografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '42', 'Ingeniero en Geodesia y Cartografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '115', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '116', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '117', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '165', 'Doctorado Topografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '180', 'Máster en Ingeniería en Geodesia y Cartografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '197', 'Programa Movilidad ETSI Topografía, Geodisa y Cartografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '202', 'Grado en Ingeniería Geomática y Topografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '306', 'Máster Universitario en Ingeniería Geodésica y Cartografía');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '508', 'Grado en Ingeniería Geomática');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '509', 'Grado en Ingeniería de las Tecnologías de la Información Geoespacial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('18', '510', 'Máster Oficial en Análisis del Riesgo Sísmico mediante Tecnologías Geoespaciales');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('19', 'Facultad de Ciencias de la Actividad Física y del Deporte (INEF)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '47', 'Licenciado en CC. de la Actividad Física y del Deporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '48', 'Grado en Ciencias de la Actividad Física y del Deporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '118', 'Máster Oficial');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '119', 'Máster Habilitante');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '120', 'Máster Titulo Propio');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '177', 'Doctorado INEF');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '205', 'Programa Movilidad Facultad de Ciencias de la Actividad Física y del Deporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '244', 'Máster Universitario en Dirección de Org. e Inst. de la Actividad Física y del Deporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '245', 'Máster Universitario en Ciencias de la Actividad Física y del Deporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '397', 'Master en entrenamiento personal');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '444', 'PREVENCION, INTERVENCION Y RECUPERACION FUNCIONAL DE LESIONES EN LA ACTIVID');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('19', '486', 'Grado en Ciencias de la Actividad Física y del Deporte');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('20', 'Centro Superior de Diseño de Moda de Madrid');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('20', '217', 'Título de Enseñanzas Artísticas Superiores');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('20', '361', 'Grado en Diseño de Moda');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('20', '432', 'Programa Movilidad Centro Superior de Diseño de Moda de Madrid');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('20', '534', 'Tecnología e Innovación en Diseño de Moda');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('20', '535', 'Máster Universitario en Tecnología e Innovación en Diseño de Moda');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('21', 'Escuela Internacional de Doctorado de la UPM');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '487', 'DOCTORADO EN INNOVACION TECNOLOGICA EN EDIFICACION');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '491', 'Doctorado en Software Sistemas y Computación de la ETSI Informáticos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '495', 'DOCTORADO EN PATRIMONIO ARQUITECTONICO');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '496', 'DOCTORADO EN INGENIERIA DE ESTRUCTURAS, CIMENTACIONES Y MATERIALES');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '497', 'DOCTORADO EN INGENIERIA DE PRODUCCION Y DISEÑO INDUSTRIAL');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '498', 'DOCTORADO EN INGENIERIA BIOMEDICA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '500', 'DOCTORADO EN INNOVACION TECNOLOGICA EN EDIFICACION');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '502', 'DOCTORADO EN INGENIERIA GEOMATICA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '504', 'DOCTORADO EN ARQUITECTURA Y URBANISMO');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '505', 'DOCTORADO EN INGENIERIA DE SISTEMAS TELEMATICOS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '506', 'DOCTORADO TECNOLOGIA AGROAMBIENTAL PARA UNA AGRICULTURA SOSTENIBLE');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '507', 'DOCTORADO EN INGENIERIA MECANICA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '512', 'DOCTORADO EN AUTOMATICA Y ROBOTICA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '520', 'PROYECTOS ARQUITECTONICOS AVANZADOS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '523', 'DOCTORADO EN INGENIERIA Y GESTION DEL MEDIO NATURAL');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '524', 'DOCTORADO EN CONSTRUCCION Y TECNOLOGIA ARQUITECTONICAS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '527', 'DOCTORADO EN ECOLOGIA. CONSERVACION Y RESTAURACION DE ECOSISTEMAS');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '528', 'Doctorado en Arquitectura, Diseño, Moda &amp; Sociedad');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '530', 'DOCTORADO EN COMUNICACION ARQUITECTONICA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '536', 'DOCTORADO EN CIENCIAS Y TECNOLOGIAS DE LA COMPUTACION PARA SMART CITIES');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('21', '539', 'DOCTORADO EN INGENIERIA AMBIENTAL, QUIMICA Y DE LOS MATERIALES');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('22', 'EPES');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('23', 'Centro Virtual Master Universitario en Eficiencia Energética en la Edificación, Industria y Transporte');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('23', '344', 'Master en Eficiencia Energética en la Edificación, la Industria y el Transporte');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('24', 'Instituto Universitario de Investigación de Automóviles');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('24', '404', 'Máster en Ingeniería de Automoción');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('24', '405', 'Máster en Ingeniería de los Vehículos Híbridos y Eléctricos');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('24', '450', 'Master en Ingeniería de vehículos autónomos y conectados');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('25', 'MASTER UNIVERSITARIO EN CIBERSEGURIDAD (MUCS)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('25', '438', 'Máster Universitario en Ciberseguridad');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('26', 'Rectorado');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('26', '433', 'Especialización en Gestion de Empresas');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('26', '470', 'LIDERAZGO INTERNACIONAL EN INGENIERÍA Y ARQUITECTURA');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('26', '480', 'EXPERTO EN ORGANIZACIONES INTELIGENTES HACIA LA TRANSFORMACION DIGITAL');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('26', '488', 'Especialización en Organizaciones Inteligentes hacia la Trasformacion Digital');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('27', 'ICE');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('27', '221', 'Master Universitario en formación del Profesorado de Educación Secundaria, Bachillerato y Formación Profesonal');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('27', '310', 'Formación del Profesorado en E.S.O. y Bachillerato (Esp. Educación Física)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('27', '311', 'Formación del Profesorado en E.S.O. y Bachillerato (Esp. Expresión Gráfica))');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('27', '312', 'Formación del Profesorado en E.S.O. y Bachillerato (Esp. Tecnología)');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('27', '319', 'Máster en Gestión y Dirección Hotelera');

INSERT INTO `gespracti`.`sedes` ('ID_SEDE', 'NOMBRE') VALUES ('28', 'Centro Virtual: Máster en Energías Renovables y Medio Ambiente');
INSERT INTO `gespracti`.`titulaciones` ('ID_SEDE', 'ID_TITULACION', 'NOMBRE') VALUES ('28', '331', 'Máster en Energías Renovables y Medio Ambiente');

