-- Table USUARIOS

CREATE TABLE `USUARIOS`
(
  `ID_USUARIO` Int NOT NULL,
  `LOGIN` Varchar(20) NOT NULL,
  `PASSWORD` Varchar(20) NOT NULL,
  `CAMBIAR_PASSWORD` Varchar(1)
)
;

ALTER TABLE `USUARIOS` ADD PRIMARY KEY (`ID_USUARIO`)
;

-- Table ROLES

CREATE TABLE `ROLES`
(
  `ID_ROL` Int NOT NULL,
  `NOMBRE_ROL` Varchar(20)
)
;

ALTER TABLE `ROLES` ADD PRIMARY KEY (`ID_ROL`)
;

-- Table ROLES_USUARIOS

CREATE TABLE `ROLES_USUARIOS`
(
  `ID_USUARIO` Int NOT NULL,
  `ID_ROL` Int NOT NULL
)
;

ALTER TABLE `ROLES_USUARIOS` ADD PRIMARY KEY (`ID_USUARIO`,`ID_ROL`)
;


-- Table EMPRESAS

CREATE TABLE `EMPRESAS`
(
  `ID_EMPRESA` Int NOT NULL AUTO_INCREMENT,
  `TIPO_DOCUMENTO` Int NOT NULL,
  `NIF_NIE` Varchar(9) NOT NULL,
  `DENOMINACION_SOCIAL` Varchar(200) NOT NULL,
  `DENOMINACION_COMERCIAL` Varchar(200),
  `TIPO_PERSONA_JURIDICA` Int NOT NULL,
  `DOMICILIO_FISCAL` Varchar(200),
  `PERSONA_CONTACTO` Varchar(100) NOT NULL,
  `CARGO_PERSONA_CONTACTO` Varchar(200),
  `EMAIL` Varchar(100) NOT NULL,
  `TELEFONO` Varchar(20) NOT NULL,
  `NUM_EMPLEADOS` Int,
  `SECTOR_ACTIVIDAD` Int,
  `URL_WEB` Varchar(200),
  `DESCRIPCION_ACTIVIDAD` Varchar(1000) NOT NULL,
  `UBICACION_CENTRO_TRABAJO` Varchar(200),
  `REPRESENTANTE_LEGAL` Varchar(200),
  `CARGO_REPRESENTANTE` Varchar(200),
  `FECHA_ESCRITURA` Date,
  `NOTARIO` Varchar(200),
  `LOCALIDAD_NOTARIO` Varchar(20),
  `DIRECCION` Varchar(200) NOT NULL,
  `MUNICIPIO` Varchar(200) NOT NULL,
  `PROVINCIA` Varchar(20) NOT NULL,
  `COD_POSTAL` Varchar(10) NOT NULL,
  `PAIS` Int NOT NULL,
  `PERSONA_CONTACTO_CONTABILIDAD` Varchar(200),
  `EMAIL_CONTABILIDAD` Varchar(200),
  `TELEFONO_CONTABILIDAD` Varchar(20),
  `MESES_FACTURA` Int,
  `ALUMNOS_FACTURA` Int,
  PRIMARY KEY (`ID_EMPRESA`)
)
;

CREATE TABLE `ESTUDIANTES`
(
  `ID_ESTUDIANTE` Int NOT NULL AUTO_INCREMENT,
  `NOMBRE` Varchar(200) NOT NULL,
  `APELLIDO1` Varchar(200) NOT NULL,
  `APELLIDO2` Varchar(200),
  `SEXO` Int,
  `FECHA_NACIMIENTO` Date NOT NULL,
  `DNI_NIE` Varchar(20) NOT NULL,
  `TIPO_DOCUMENTO` Int NOT NULL,
  `EMAIL` Varchar(200) NOT NULL,
  `TELEFONO` Varchar(10) NOT NULL,
  `DIRECCION` Varchar(200) NOT NULL,
  `MUNCIPIO` Varchar(200) NOT NULL,
  `PROVINCIA` Varchar(20) NOT NULL,
  `COD_POSTAL` Varchar(20) NOT NULL,
  `PAIS` Int NOT NULL,
  `NACIONALIDAD` Varchar(200) NOT NULL,
  `GRADO_MINUSVALIA` Int,
  `TITULACION_UPM` Int NOT NULL,
  `FECHA_INICIO` Date NOT NULL,
  `FECHA_FIN` Date NOT NULL,
  PRIMARY KEY (`ID_ESTUDIANTE`)
)
;


-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE `ROLES_USUARIOS` ADD CONSTRAINT `FK_ROLS_USU_USUARIOS` FOREIGN KEY (`ID_USUARIO`) REFERENCES `USUARIOS` (`ID_USUARIO`) ON DELETE RESTRICT ON UPDATE RESTRICT
;


ALTER TABLE `ROLES_USUARIOS` ADD CONSTRAINT `FK_ROLS_USU_ROLES` FOREIGN KEY (`ID_ROL`) REFERENCES `ROLES` (`ID_ROL`) ON DELETE RESTRICT ON UPDATE RESTRICT
;